apiVersion: v1
kind: ConfigMap
metadata:
  name: oblivion-api-config
  labels:
    app: oblivion-api
data:
  OBLIVION_DYNAMODB_ENDPOINT: http://oblivion-dynamodb-local:8000
  OBLIVION_DYNAMODB_REGION: us-east-1
  OBLIVION_DYNAMODB_TABLE_NAME: oblivion_messages