apiVersion: apps/v1
kind: Deployment
metadata:
  name: oblivion-api
  labels:
    app: oblivion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oblivion-api
  template:
    metadata:
      labels:
        app: oblivion-api
    spec:
      containers:
        - name: api
          image: localhost:32000/oblivion-api:latest
          imagePullPolicy: Always
          env:
            - name: OBLIVION_DYNAMODB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: oblivion-api-config
                  key: OBLIVION_DYNAMODB_ENDPOINT
                  optional: true
            - name: OBLIVION_DYNAMODB_REGION
              valueFrom:
                configMapKeyRef:
                  name: oblivion-api-config
                  key: OBLIVION_DYNAMODB_REGION
            - name: OBLIVION_DYNAMODB_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: oblivion-api-config
                  key: OBLIVION_DYNAMODB_TABLE_NAME
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
