apiVersion: v1
kind: Service
metadata:
  name: oblivion-dynamodb-local
  labels:
    app: oblivion-dynamodb-local
spec:
  selector:
    app: oblivion-dynamodb-local
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP