apiVersion: apps/v1
kind: Deployment
metadata:
  name: oblivion-dynamodb-local
  labels:
    app: oblivion-dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oblivion-dynamodb-local
  template:
    metadata:
      labels:
        app: oblivion-dynamodb-local
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:3.3.0
          args:
            - -jar
            - DynamoDBLocal.jar
            - -sharedDb
            - -inMemory
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi