%dev.oblivion.dynamodb.endpoint=http://localhost:8000
oblivion.dynamodb.region=us-east-1
oblivion.dynamodb.table-name=oblivion_messages
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl\,software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy
